### ISSUE TITLE
Channel launch todo

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/intercom#1]
- [x] Code Review
- [x] Add @ftw-soft as repo admin
- [x] Add to website
- [x] Create packagist package
- [x] StyleCI
- [x] Travis

**Comment by atymic** [comment]
@ftw-soft 

Have pushed the package to packagist :)
https://packagist.org/packages/laravel-notification-channels/intercom

**Comment by ftw-soft** [comment]
Could you please a corred style.ci link for shield on the README.md?

**Comment by atymic** [comment]
Done :)

**Comment by ftw-soft** [comment]
I'll make a release tag now

**Comment by atymic** [comment]
Awesome :) 

I'll make a PR to add it to the website tomorrow
